server:
  servlet:
    context-path: /wukang
  port: 80

spring:
  datasource:
    #基础配置
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wukang
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #其他配置
    initialSize: 5
    minIdle: 5
    maxWait: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    filter: stat,wall,log4j
    maxPoolPreparedStatementPerConnnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;durid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

